from flask import Flask, render_template

app = Flask(__name__)

allClubs = ["ACM (Association for Computing Machinery)",
"Acts 2 Christian Fellowship",
"African Student Association",
"AGES (Association of Graduate Engineering Students)",
"AI Collaborate",
"Alpha Kappa Psi",
"Alpha Phi Omega",
"Alpha Psi Omega",
"American Civil Liberties Union (ACLU)",
"American Constitution Society Santa Clara",
"American Institute of Aeronautics and Astronautics",
"American Sign Language Club",
"American Society of Mechanical Engineers",
"APALSA",
"Armenian Students Association",
"Art Law Society",
"Artificial Intelligence Student Association (AISA)",
"Asian & Pacific-Islander Student Union",
"Associated General Contractors of America",
"Association for Computing Machinery - Women's Chapter",
"Banda Seleccion de Santa Clara",
"Barkada of SCU",
"Be the Match On Campus SCU", "Belles Service Organization", 
"Biomedical Engineering Society", "Bird Up! SCU", 
"Black Business Association",
"Blockchain & Compliance Legal Society",
"BLSA (The Black Law Student  Association)", 
"Blueprints for Pangea",
"Bread Lover's Club",
"Bronco Foodie Club",
"Broncos for Life"
"C.A.E.S.A.R",
"Camp Kesem at Santa Clara University",
"Cannabis Law and Policy Group",
"Card Game Club",
"Chinese Student Association",
"Chinese Students and Scholars Association",
"ChIPs (Chiefs in IP)",
"Clara Craft Club",
"Club Bio",
"College Catholics",
"Commuter Student Union",
"Core Christian Fellowship",
"Criminal Law Society",
"Cultural Italian American Organization",
"DayBreak K-Pop Dance Crew",
"Delta Epsilon Mu, Inc",
"Delta Sigma Pi",
"Dynamic Rhythm",
"Economics Student Association",
"Engineers Without Borders",
"Environmental Law Society",
"EQSCU (Equality at Santa Clara Law)",
"Ethnic Studies Club",
"Finance Association",
"French Club",
"Future Child Advocates",
"GetVirtual",
"Graduate Finance Club",
"Graduate Real Estate Club",
"Grass Roots Environmental Efforts Now",
"Hermanas Unidas de SCU",
"Homeless Outreach Association",
"Hua Xia Student Society",
"IGNITE SCU",
"Igwebuike",
"Information Systems and Analytics Student Network",
"Intandesh",
"International Student Club",
"Internet Law Student  Organization",
"ISN (ISA Student Network)",
"Japanese Student Assosciation",
"Jewish Student Union",
"Ka Mana’o O Hawai’i",
"Klesis Christian Fellowship",
"Korean Student Association (KSA)",
"Lambda Pi Eta",
"Language Learning Club",
"LatinX Business Student Association",
"Latinx Student Union",
"Law and Business Society",
"Leavey Black Business Association",
"LSBISA - Leavey School of Business International Student Association",
"Mathematics and Computer Science Society of Santa Clara University",
"MBA Student Advisory Council (MBA SAC)",
"Middle Eastern North African Club",
"Muslim Student Association",
"National Society of Black Engineers",
"Native American Coalition for Change",
"Net Impact SCU Graduate Chapter",
"NetImpact Graduate Chaper",
"Neuroscience Club",
"New Life on Campus",
"Oceans & Rivers Conservation Alliance",
"OneUp Org",
"Partners In Health Engage",
"Partnership for Animal Welfare and Support (PAWS)",
"Phi Chi Theta",
"Pi Tau Sigma Mechanical Engineering Honor Society",
"Pickleball Club",
"Pre-Law Society",
"Pre-Physician Assistant Club",
"Psychology Club",
"Public Health Club",
"Public Health Club",
"Queer and Qualified",
"Queer People Of Color Association",
"Real Estate Association",
"Recipes for Relief Initiative",
"Retail Studies Student Association",
"Rho Psi Eta",
"Russian Speaking Club",
"Salsa Clara de SCU",
"Santa Clara Ballroom Dance Association",
"Santa Clara Chapter of Engineers Without Borders",
"Santa Clara Consulting",
"Santa Clara Dance Coalition",
"Santa Clara Entrepreneurship Association",
"Santa Clara Formula SAE",
"Santa Clara Gaming & Esports",
"Santa Clara Investment Club",
"Santa Clara Mindfullness",
"Santa Clara Rock Climbing Club",
"santa clara skate club",
"Santa Clara Sunrise",
"Santa Clara University Accounting Association",
"Santa Clara University Associated General Contractors of America",
"Santa Clara University Chess Club",
"Santa Clara University Filmmakers' Club",
"Santa Clara University Finance Association",
"Santa Clara University Mock Trial",
"Santa Clara University Model United Nations",
"Santa Clara University Photography Club",
"Santa Clara University Pre-Dental Society",
"Santa Clara University Student Art League",
"Santa Clara University Student Chapter of the Association for Women in Mathematics",
"Santa Clara University Table Tennis Club",
"Santa Clara Venture Capital Association",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
]
allClubs = sorted(allClubs)

@app.route('/')
def index():
   

    # Pass the content to the template for rendering
    return render_template('index.html', allClubs=allClubs)

if __name__ == '__main__':
    app.run(debug=True)

